version: '3.8'

services:
  main:
    container_name: "${APP_NAME}-main"
    build: .docker/php
    entrypoint: .docker/entrypoint.sh
    environment:
      - COMPOSER_MEMORY_LIMIT=2G
      - TZ=${APP_TIMEZONE}
    volumes:
      - .:/var/www
    networks:
      - laravel10-notification-network
    depends_on:
      - mysql

  nginx:
    container_name: "${APP_NAME}-nginx"
    build: .docker/nginx
    restart: unless-stopped
    tty: true
    ports:
      - ${APP_PORT}:80
    environment:
      - TZ=${APP_TIMEZONE}
    volumes:
      - .:/var/www
    networks:
      - laravel10-notification-network
    depends_on:
      - main

  redis:
    container_name: "${APP_NAME}-redis"
    build: .docker/redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - laravel10-notification-network

  mysql:
    container_name: "${APP_NAME}-mysql"
    build: .docker/mysql
    platform: linux/amd64
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT_EXTERNAL}:${DB_PORT}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
      - ./.docker/mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - laravel10-notification-network

networks:
  laravel10-notification-network:
    driver: bridge
